/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.54
 * Generated at: 2026-05-10 11:16:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.*;
import java.util.*;

public final class game_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("model");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Trận đấu — Battleship</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar\">\r\n");
      out.write("  <span class=\"logo\">⚓ BATTLESHIP</span>\r\n");
      out.write("  <nav>\r\n");
      out.write("    <span style=\"color:var(--text-muted);font-size:0.9rem\">👤 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.playerName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/history\">Lịch sử</a>\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/leaderboard\">BXH</a>\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\">Đăng xuất</a>\r\n");
      out.write("  </nav>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");

  Board playerBoard = (Board) session.getAttribute("board");
  GameState gs = (GameState) session.getAttribute("gameState");
  String mode = (String) session.getAttribute("mode");
  String p2Name = (String) session.getAttribute("player2Name");
  if (p2Name == null) p2Name = "Người chơi 2";
  String p1Name = (String) session.getAttribute("playerName");
  if (p1Name == null) p1Name = "Người chơi 1";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"game-wrapper\">\r\n");
      out.write("  <div class=\"game-header\">\r\n");
      out.write("    <h1>⚔ ");
      out.print( "PvE".equals(mode) ? "Chơi với AI" : "PvP — 2 Người chơi" );
      out.write("</h1>\r\n");
      out.write("    <div style=\"display:flex;align-items:center;gap:12px\">\r\n");
      out.write("      <div id=\"turn-indicator\" class=\"turn-indicator\">⚔ Lượt của bạn</div>\r\n");
      out.write("      <div id=\"turn-timer\" class=\"turn-timer\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"display:flex;gap:8px\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/setup\" class=\"btn btn-secondary btn-sm\">🔄 Ván mới</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"boards-container\">\r\n");
      out.write("    <!-- Enemy board -->\r\n");
      out.write("    <div class=\"board-area enemy-board\">\r\n");
      out.write("      <h2>🎯 Lưới địch — bắn vào đây</h2>\r\n");
      out.write("      <div class=\"grid-container\">\r\n");
      out.write("        <div class=\"grid-header\">\r\n");
      out.write("          ");
 String[] c2 = {"A","B","C","D","E","F","G","H","I","J"};
             for(String c : c2) { 
      out.write("<div class=\"grid-label\">");
      out.print(c);
      out.write("</div>");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 for(int y=0;y<10;y++) { 
      out.write("\r\n");
      out.write("        <div class=\"grid-row\">\r\n");
      out.write("          <div class=\"grid-row-label\">");
      out.print(y+1);
      out.write("</div>\r\n");
      out.write("          ");
 for(int x=0;x<10;x++) { 
      out.write("\r\n");
      out.write("          <div class=\"grid-cell\" id=\"enemy-");
      out.print(x);
      out.write('-');
      out.print(y);
      out.write("\"\r\n");
      out.write("               onclick=\"");
      out.print( "PvP".equals(mode) ? "fireShotPvP(" + x + "," + y + ")" : "fireShot(" + x + "," + y + ")" );
      out.write("\"\r\n");
      out.write("               title=\"");
      out.print(c2[x]);
      out.print(y+1);
      out.write("\"></div>\r\n");
      out.write("          ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Player board -->\r\n");
      out.write("    <div class=\"board-area my-board\">\r\n");
      out.write("      <h2>🛡 Lưới của bạn</h2>\r\n");
      out.write("      <div class=\"grid-container\">\r\n");
      out.write("        <div class=\"grid-header\">\r\n");
      out.write("          ");
 for(String c : c2) { 
      out.write("<div class=\"grid-label\">");
      out.print(c);
      out.write("</div>");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 for(int y=0;y<10;y++) { 
      out.write("\r\n");
      out.write("        <div class=\"grid-row\">\r\n");
      out.write("          <div class=\"grid-row-label\">");
      out.print(y+1);
      out.write("</div>\r\n");
      out.write("          ");
 for(int x=0;x<10;x++) {
            String cls = "grid-cell";
            if (playerBoard != null && playerBoard.getCells() != null) {
              Cell cell = playerBoard.getCells()[x][y];
              if (cell != null) {
                if (cell.isHit() && cell.isHasShip()) cls += " hit-ship";
                else if (cell.isHit()) cls += " miss";
                else if (cell.isHasShip()) cls += " has-ship";
              }
            }
          
      out.write("\r\n");
      out.write("          <div class=\"");
      out.print(cls);
      out.write("\" id=\"my-");
      out.print(x);
      out.write('-');
      out.print(y);
      out.write("\"></div>\r\n");
      out.write("          ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Log -->\r\n");
      out.write("  <div>\r\n");
      out.write("    <p style=\"color:var(--text-muted);font-size:0.85rem;margin-bottom:8px;text-transform:uppercase;letter-spacing:1px\">📋 Nhật ký chiến đấu</p>\r\n");
      out.write("    <div class=\"game-log\" id=\"game-log\">\r\n");
      out.write("      <div class=\"log-entry\" style=\"color:var(--text-muted)\">Trận đấu bắt đầu. Chúc may mắn! 🚀</div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- PvP: Player 2 setup overlay -->\r\n");
 if ("PvP".equals(mode)) { 
      out.write("\r\n");
      out.write("<div id=\"pvp-setup-overlay\" class=\"modal-overlay\" style=\"display:none\">\r\n");
      out.write("  <div class=\"modal pvp-setup-modal\">\r\n");
      out.write("    <h2 id=\"pvp-setup-title\" style=\"margin-bottom:16px\">Người chơi 2 — Đặt thuyền</h2>\r\n");
      out.write("    <div style=\"display:flex;gap:20px;align-items:flex-start;flex-wrap:wrap;justify-content:center\">\r\n");
      out.write("      <!-- Ship list -->\r\n");
      out.write("      <div class=\"ship-panel\" style=\"min-width:160px\">\r\n");
      out.write("        <h3>📦 Thuyền</h3>\r\n");
      out.write("        <div id=\"pvp-ship-list\">\r\n");
      out.write("          <div class=\"ship-item pvp-ship-item\" data-idx=\"0\" onclick=\"pvpSelectShip(0)\"><div class=\"ship-dots\" id=\"pvp-dots-0\"></div><span>Carrier (5)</span></div>\r\n");
      out.write("          <div class=\"ship-item pvp-ship-item\" data-idx=\"1\" onclick=\"pvpSelectShip(1)\"><div class=\"ship-dots\" id=\"pvp-dots-1\"></div><span>Battleship (4)</span></div>\r\n");
      out.write("          <div class=\"ship-item pvp-ship-item\" data-idx=\"2\" onclick=\"pvpSelectShip(2)\"><div class=\"ship-dots\" id=\"pvp-dots-2\"></div><span>Cruiser (3)</span></div>\r\n");
      out.write("          <div class=\"ship-item pvp-ship-item\" data-idx=\"3\" onclick=\"pvpSelectShip(3)\"><div class=\"ship-dots\" id=\"pvp-dots-3\"></div><span>Submarine (3)</span></div>\r\n");
      out.write("          <div class=\"ship-item pvp-ship-item\" data-idx=\"4\" onclick=\"pvpSelectShip(4)\"><div class=\"ship-dots\" id=\"pvp-dots-4\"></div><span>Destroyer (2)</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"margin-top:12px;display:flex;flex-direction:column;gap:6px\">\r\n");
      out.write("          <button id=\"pvp-dir-btn\" class=\"btn btn-secondary btn-sm\" onclick=\"pvpToggleDir()\">↔ Ngang</button>\r\n");
      out.write("          <button class=\"btn btn-secondary btn-sm\" onclick=\"pvpResetSetup()\">🔄 Đặt lại</button>\r\n");
      out.write("          <button class=\"btn btn-secondary btn-sm\" onclick=\"pvpAutoPlace()\">⚡ Tự động</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Grid -->\r\n");
      out.write("      <div>\r\n");
      out.write("        <div class=\"grid-container\" id=\"pvp-setup-grid\">\r\n");
      out.write("          <div class=\"grid-header\">\r\n");
      out.write("            ");
 String[] cols2 = {"A","B","C","D","E","F","G","H","I","J"};
               for(String c : cols2) { 
      out.write("<div class=\"grid-label\">");
      out.print(c);
      out.write("</div>");
 } 
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          ");
 for(int y=0;y<10;y++) { 
      out.write("\r\n");
      out.write("          <div class=\"grid-row\">\r\n");
      out.write("            <div class=\"grid-row-label\">");
      out.print(y+1);
      out.write("</div>\r\n");
      out.write("            ");
 for(int x=0;x<10;x++) { 
      out.write("\r\n");
      out.write("            <div class=\"grid-cell\" id=\"pvp-setup-");
      out.print(x);
      out.write('-');
      out.print(y);
      out.write("\"\r\n");
      out.write("                 onclick=\"pvpSetupCellClick(");
      out.print(x);
      out.write(',');
      out.print(y);
      out.write(")\"\r\n");
      out.write("                 onmouseenter=\"pvpSetupCellHover(");
      out.print(x);
      out.write(',');
      out.print(y);
      out.write(")\"\r\n");
      out.write("                 onmouseleave=\"pvpSetupCellHover(-1,-1)\"></div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"margin-top:12px;text-align:center\">\r\n");
      out.write("          <button class=\"btn btn-success\" onclick=\"submitPvPSetup2()\">▶ Sẵn sàng chiến đấu!</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- PvP: Screen handover overlay -->\r\n");
      out.write("<div id=\"pvp-turn-overlay\" class=\"modal-overlay\" style=\"display:none\">\r\n");
      out.write("  <div class=\"modal\" style=\"text-align:center;max-width:400px\">\r\n");
      out.write("    <div style=\"font-size:3rem;margin-bottom:12px\">🎮</div>\r\n");
      out.write("    <h2 id=\"pvp-turn-name\" style=\"margin-bottom:8px\">Người chơi 1, đến lượt bạn!</h2>\r\n");
      out.write("    <p id=\"pvp-turn-hint\" style=\"color:var(--text-muted);margin-bottom:24px\">Đưa màn hình cho người chơi, rồi nhấn Sẵn sàng.</p>\r\n");
      out.write("    <button class=\"btn btn-primary\" style=\"font-size:1.1rem;padding:12px 32px\" onclick=\"pvpReady()\">✅ Sẵn sàng</button>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- End game modal -->\r\n");
      out.write("<div id=\"end-modal\" class=\"modal-overlay\" style=\"display:none\">\r\n");
      out.write("  <div class=\"modal\">\r\n");
      out.write("    <div style=\"font-size:3.5rem;margin-bottom:12px\">🎉</div>\r\n");
      out.write("    <h2 class=\"result-title win\" id=\"modal-title\">Bạn thắng!</h2>\r\n");
      out.write("    <p id=\"modal-subtitle\" style=\"color:var(--text-muted);margin:8px 0 24px\"></p>\r\n");
      out.write("    <div style=\"display:flex;gap:12px;justify-content:center\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/setup\" class=\"btn btn-primary\">🔄 Chơi lại</a>\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/history\" class=\"btn btn-secondary\">📋 Lịch sử</a>\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/leaderboard\" class=\"btn btn-secondary\">🏆 BXH</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/game.js\"></script>\r\n");
      out.write("<script>\r\n");
 if ("PvP".equals(mode)) { 
      out.write("\r\n");
      out.write("// Render pvp ship dots\r\n");
      out.write("[5,4,3,3,2].forEach((len,i) => {\r\n");
      out.write("  const el = document.getElementById('pvp-dots-' + i);\r\n");
      out.write("  if (el) for(let d=0;d<len;d++){const dot=document.createElement('div');dot.className='ship-dot';el.appendChild(dot);}\r\n");
      out.write("});\r\n");
      out.write("// Load P1 ships from session & init PvP\r\n");
      out.write("const p1Ships = ");
      out.print( session.getAttribute("shipsJson") != null ? session.getAttribute("shipsJson") : "[]" );
      out.write(";\r\n");
      out.write("initPvP('");
      out.print(p1Name);
      out.write("', '");
      out.print(p2Name);
      out.write("', p1Ships);\r\n");
      out.write("init('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', 'PvP');\r\n");
 } else { 
      out.write("\r\n");
      out.write("init('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', 'PvE');\r\n");
 } 
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
