/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.54
 * Generated at: 2026-05-10 12:59:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;

public final class leaderboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Bảng xếp hạng — Battleship</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar\">\r\n");
      out.write("  <span class=\"logo\">⚓ BATTLESHIP</span>\r\n");
      out.write("  <nav>\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/setup\">🎮 Chơi</a>\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/history\">📋 Lịch sử</a>\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\">Đăng xuất</a>\r\n");
      out.write("  </nav>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"page-wrapper\">\r\n");
      out.write("  <h1>🏆 Bảng xếp hạng</h1>\r\n");
      out.write("\r\n");
      out.write("  ");
 List<Map<String,Object>> top = (List<Map<String,Object>>) request.getAttribute("topPlayers");
     String myName = (String) session.getAttribute("playerName");
  
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");
 if (top == null || top.isEmpty()) { 
      out.write("\r\n");
      out.write("  <div style=\"text-align:center;padding:60px;color:var(--text-muted);\">\r\n");
      out.write("    <div style=\"font-size:3rem;margin-bottom:12px\">🏆</div>\r\n");
      out.write("    <p>Chưa có dữ liệu xếp hạng.<br><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/setup\">Hãy chơi và ghi điểm!</a></p>\r\n");
      out.write("  </div>\r\n");
      out.write("  ");
 } else { 
      out.write("\r\n");
      out.write("  <table>\r\n");
      out.write("    <thead>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th>Hạng</th>\r\n");
      out.write("        <th>Người chơi</th>\r\n");
      out.write("        <th>Thắng</th>\r\n");
      out.write("        <th>Thua</th>\r\n");
      out.write("        <th>Tổng trận</th>\r\n");
      out.write("        <th>Tỉ lệ thắng</th>\r\n");
      out.write("        <th>Điểm cao nhất</th>\r\n");
      out.write("        <th>Tổng điểm</th>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("    <tbody>\r\n");
      out.write("    ");
 for (Map<String,Object> row : top) {
        int rank = (int) row.get("rank");
        String username = (String) row.get("username");
        boolean isMe = username != null && username.equals(myName);
        String rankClass = rank == 1 ? "rank-1" : rank == 2 ? "rank-2" : rank == 3 ? "rank-3" : "";
        String medal = rank == 1 ? "🥇" : rank == 2 ? "🥈" : rank == 3 ? "🥉" : "";
    
      out.write("\r\n");
      out.write("      <tr style=\"");
      out.print( isMe ? "background:rgba(59,130,246,0.08)" : "" );
      out.write("\">\r\n");
      out.write("        <td class=\"");
      out.print( rankClass );
      out.write('"');
      out.write('>');
      out.print( medal );
      out.write(' ');
      out.write('#');
      out.print( rank );
      out.write("</td>\r\n");
      out.write("        <td style=\"font-weight:");
      out.print( isMe ? "700" : "400" );
      out.write("\">\r\n");
      out.write("          ");
      out.print( username );
      out.write(' ');
      out.print( isMe ? "<span style='color:var(--accent);font-size:0.8rem'>(Bạn)</span>" : "" );
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("        <td style=\"color:var(--success)\">");
      out.print( row.get("total_wins") );
      out.write("</td>\r\n");
      out.write("        <td style=\"color:var(--danger)\">");
      out.print( row.get("total_losses") );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( row.get("total_games") );
      out.write("</td>\r\n");
      out.write("        <td style=\"color:var(--accent)\">");
      out.print( row.get("win_rate") );
      out.write("%</td>\r\n");
      out.write("        <td style=\"color:var(--warning);font-weight:600\">");
      out.print( row.get("best_score") );
      out.write("</td>\r\n");
      out.write("        <td style=\"color:var(--text-muted)\">");
      out.print( row.get("total_score") );
      out.write("</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    </tbody>\r\n");
      out.write("  </table>\r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
