/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.54
 * Generated at: 2026-05-10 11:15:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import jakarta.servlet.http.HttpSession;

public final class setup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("jakarta.servlet.http.HttpSession");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <title>Thiết lập trận đấu — Battleship</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("  <style>\r\n");
      out.write("    @keyframes shake {\r\n");
      out.write("      0%,100%{transform:translateX(0)} 20%,60%{transform:translateX(-6px)} 40%,80%{transform:translateX(6px)}\r\n");
      out.write("    }\r\n");
      out.write("    .setup-controls { display:flex; gap:10px; margin-bottom:16px; flex-wrap:wrap; }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar\">\r\n");
      out.write("  <span class=\"logo\">⚓ BATTLESHIP</span>\r\n");
      out.write("  <nav>\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/history\">Lịch sử</a>\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/leaderboard\">BXH</a>\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\">Đăng xuất</a>\r\n");
      out.write("  </nav>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"setup-wrapper\">\r\n");
      out.write("  <h1>⚙ Thiết lập trận đấu</h1>\r\n");
      out.write("\r\n");
      out.write("  ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("  <div class=\"alert alert-error\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Mode selection -->\r\n");
      out.write("  <p style=\"color:var(--text-muted);margin-bottom:12px;font-size:0.9rem;\">Chọn chế độ chơi:</p>\r\n");
      out.write("  <div class=\"mode-cards\" id=\"mode-cards\">\r\n");
      out.write("    <div class=\"mode-card selected\" onclick=\"selectMode('PvE',this)\">\r\n");
      out.write("      <div class=\"mode-icon\">🤖</div>\r\n");
      out.write("      <h3>Chơi với AI</h3>\r\n");
      out.write("      <p>Thách đấu máy tính với 2 cấp độ</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"mode-card\" onclick=\"selectMode('PvP',this)\">\r\n");
      out.write("      <div class=\"mode-icon\">👥</div>\r\n");
      out.write("      <h3>Chơi 2 người</h3>\r\n");
      out.write("      <p>Luân phiên trên cùng máy</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div id=\"p2name-row\" style=\"display:none;margin-bottom:16px\">\r\n");
      out.write("    <p style=\"color:var(--text-muted);margin-bottom:8px;font-size:0.9rem;\">Tên Người chơi 2:</p>\r\n");
      out.write("    <input type=\"text\" id=\"p2name-input\" class=\"input-field\" placeholder=\"Người chơi 2\" style=\"max-width:260px\">\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div id=\"difficulty-row\" style=\"margin-bottom:20px;\">\r\n");
      out.write("    <p style=\"color:var(--text-muted);margin-bottom:8px;font-size:0.9rem;\">Độ khó AI:</p>\r\n");
      out.write("    <div style=\"display:flex;gap:10px;\">\r\n");
      out.write("      <button class=\"btn btn-secondary selected-diff\" id=\"diff-easy\" onclick=\"selectDiff('Easy')\" style=\"border-color:var(--accent)\">🟢 Dễ</button>\r\n");
      out.write("      <button class=\"btn btn-secondary\" id=\"diff-hard\" onclick=\"selectDiff('Hard')\">🔴 Khó (Hunt-Target)</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"setup-grid-area\">\r\n");
      out.write("    <div class=\"ship-panel\">\r\n");
      out.write("      <h3>📦 Thuyền của bạn</h3>\r\n");
      out.write("      <div id=\"ship-list\">\r\n");
      out.write("        <div class=\"ship-item\" data-idx=\"0\" onclick=\"selectShip(0)\">\r\n");
      out.write("          <div class=\"ship-dots\" id=\"dots-0\"></div>\r\n");
      out.write("          <span>Carrier (5)</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"ship-item\" data-idx=\"1\" onclick=\"selectShip(1)\">\r\n");
      out.write("          <div class=\"ship-dots\" id=\"dots-1\"></div>\r\n");
      out.write("          <span>Battleship (4)</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"ship-item\" data-idx=\"2\" onclick=\"selectShip(2)\">\r\n");
      out.write("          <div class=\"ship-dots\" id=\"dots-2\"></div>\r\n");
      out.write("          <span>Cruiser (3)</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"ship-item\" data-idx=\"3\" onclick=\"selectShip(3)\">\r\n");
      out.write("          <div class=\"ship-dots\" id=\"dots-3\"></div>\r\n");
      out.write("          <span>Submarine (3)</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"ship-item\" data-idx=\"4\" onclick=\"selectShip(4)\">\r\n");
      out.write("          <div class=\"ship-dots\" id=\"dots-4\"></div>\r\n");
      out.write("          <span>Destroyer (2)</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div style=\"margin-top:16px;\">\r\n");
      out.write("        <button id=\"dir-btn\" class=\"btn btn-secondary btn-sm\" onclick=\"toggleDir()\" style=\"width:100%;margin-bottom:8px\">↔ Ngang</button>\r\n");
      out.write("        <button class=\"btn btn-secondary btn-sm\" onclick=\"resetSetup()\" style=\"width:100%\">🔄 Đặt lại</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div>\r\n");
      out.write("      <div class=\"setup-controls\">\r\n");
      out.write("        <button class=\"btn btn-secondary btn-sm\" onclick=\"doAutoPlace()\">⚡ Tự động đặt</button>\r\n");
      out.write("        <button class=\"btn btn-success btn-sm\" onclick=\"submitSetup()\">▶ Bắt đầu trận đấu</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"grid-container\" id=\"setup-grid\">\r\n");
      out.write("        <div class=\"grid-header\">\r\n");
      out.write("          ");
 String[] cols = {"A","B","C","D","E","F","G","H","I","J"}; 
      out.write("\r\n");
      out.write("          ");
 for(String c : cols) { 
      out.write("<div class=\"grid-label\">");
      out.print(c);
      out.write("</div>");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 for(int y=0;y<10;y++) { 
      out.write("\r\n");
      out.write("        <div class=\"grid-row\">\r\n");
      out.write("          <div class=\"grid-row-label\">");
      out.print(y+1);
      out.write("</div>\r\n");
      out.write("          ");
 for(int x=0;x<10;x++) { 
      out.write("\r\n");
      out.write("          <div class=\"grid-cell\" id=\"setup-");
      out.print(x);
      out.write('-');
      out.print(y);
      out.write("\"\r\n");
      out.write("               onclick=\"setupCellClick(");
      out.print(x);
      out.write(',');
      out.print(y);
      out.write(")\"\r\n");
      out.write("               onmouseenter=\"setupCellHover(");
      out.print(x);
      out.write(',');
      out.print(y);
      out.write(")\"\r\n");
      out.write("               onmouseleave=\"clearHoverHighlight()\"></div>\r\n");
      out.write("          ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <form id=\"setup-form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/setup\" method=\"post\" style=\"display:none\">\r\n");
      out.write("    <input type=\"hidden\" name=\"action\" value=\"manual\" id=\"action-input\">\r\n");
      out.write("    <input type=\"hidden\" name=\"mode\" value=\"PvE\" id=\"mode-input\">\r\n");
      out.write("    <input type=\"hidden\" name=\"difficulty\" value=\"Easy\" id=\"diff-input\">\r\n");
      out.write("    <input type=\"hidden\" name=\"player2Name\" id=\"p2name-hidden\">\r\n");
      out.write("    <input type=\"hidden\" name=\"ships\" id=\"ships-input\">\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/game.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  // Render ship dots\r\n");
      out.write("  const DOTS_COUNT = [5,4,3,3,2];\r\n");
      out.write("  DOTS_COUNT.forEach((len, i) => {\r\n");
      out.write("    const el = document.getElementById('dots-' + i);\r\n");
      out.write("    if (el) for(let d=0;d<len;d++) {\r\n");
      out.write("      const dot = document.createElement('div');\r\n");
      out.write("      dot.className = 'ship-dot';\r\n");
      out.write("      el.appendChild(dot);\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  function selectMode(mode, el) {\r\n");
      out.write("    document.querySelectorAll('.mode-card').forEach(c => c.classList.remove('selected'));\r\n");
      out.write("    el.classList.add('selected');\r\n");
      out.write("    document.getElementById('mode-input').value = mode;\r\n");
      out.write("    document.getElementById('difficulty-row').style.display = mode === 'PvE' ? '' : 'none';\r\n");
      out.write("    document.getElementById('p2name-row').style.display = mode === 'PvP' ? '' : 'none';\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function selectDiff(d) {\r\n");
      out.write("    document.getElementById('diff-input').value = d;\r\n");
      out.write("    document.getElementById('diff-easy').style.borderColor = d==='Easy' ? 'var(--accent)' : '';\r\n");
      out.write("    document.getElementById('diff-hard').style.borderColor = d==='Hard' ? 'var(--accent)' : '';\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function doAutoPlace() {\r\n");
      out.write("    resetSetup();\r\n");
      out.write("    // Auto-place using JS for preview\r\n");
      out.write("    const SHIPS = [{type:'Carrier',length:5},{type:'Battleship',length:4},{type:'Cruiser',length:3},{type:'Submarine',length:3},{type:'Destroyer',length:2}];\r\n");
      out.write("    SHIPS.forEach((ship, idx) => {\r\n");
      out.write("      let placed = false, tries = 0;\r\n");
      out.write("      while (!placed && tries++ < 1000) {\r\n");
      out.write("        const x = Math.floor(Math.random()*10);\r\n");
      out.write("        const y = Math.floor(Math.random()*10);\r\n");
      out.write("        const dir = Math.random() < 0.5 ? 'H' : 'V';\r\n");
      out.write("        const prevDir = currentDir;\r\n");
      out.write("        currentDir = dir;\r\n");
      out.write("        if (canPlace(x, y, ship.length, dir)) {\r\n");
      out.write("          placeShipOnSetup(x, y, ship, idx);\r\n");
      out.write("          placed = true;\r\n");
      out.write("        } else {\r\n");
      out.write("          currentDir = prevDir;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
